### PR TITLE
set fill to none for hexagons with no value

### PR DESCRIPTION
**Pull request by danwild**
G'day, me again :)

Currently for hexbin layer - gaps in data appear as black hexagons.
This PR is to update so that if there is no value, there's no hexagon (well, no fill anyway).

Cheers,
Dan

### CODE REVIEW

**Comment by danwild** [comment]
*bump* 

(let me know if I should do anything else to get this merged in)

**Comment by reblace** [comment]
I totally didn't realize this PR was here. I'm SO SORRY :)

Anyhow, can you ensure your merge is aligned with the latest master? I've done away with bower in favor of using npm for all dependency tracking and also I've migrated to d3 v4. Your PR looks to be reintroducing the bower dependencies.

**Comment by danwild** [comment]
@reblace aha no worries that happens to me all the time ;)

mmm I had just merged your latest master in, can't see `.bowerrc`, `bower.json` files etc. in [my branch](https://github.com/danwild/leaflet-d3/tree/hexbin-gaps)  so shouldn't be any conflict?

**Comment by reblace** [comment]
It's the ./src/lib directories. If you check the master on this repo, the ./src/lib directory is now gone.

**Comment by danwild** [comment]
ah ok, just gave them the flick

**Comment by reblace** [comment]
ok, about to get some sleep, but will check this out tomorrow or later this week. Thanks for the contrbution!

**Pull request merged**
