### PR TITLE
fix #54

### LINKED ISSUE #54: Proposal new methods .hide(), .show()
I need of show and hide the d3 hexagon at runtime.. here in my new project: [keplerjs.io](http://keplerjs.io/)

```javascript
L.HexbinLayer = L.HexbinLayer.extend({
	show: function(map) {
		if(this._dataOld) {
			this._data = this._dataOld;
			delete this._dataOld;
		}
		this.redraw();
	},
	hide: function(map) {
		if(!this._dataOld) {
			this._dataOld = this._data;
			this._data = [];
		}
		this.redraw();
	}	
});
```

### PR DESCRIPTION
**Pull request by jlondonobo**
This fixes a bug where Hexbin Layers could not be toggled off using Layers Control.

[Statzg](https://github.com/statzg) proposed this fix on Issue #54.

**Example of the bug**:
hexbin_disable_720

**Behavior after implementing fix**:
done_720

### CODE REVIEW

**Comment by jlondonob** [comment]
Also fixes #68

**Comment by jlondonob** [comment]
> Could you please merge this? It works.

Unfortunately I have no write access to this repository so I cannot merge it. I've tried to contact the owner of the repo several times in the past moths and have gotten no response.

**Comment by reblace** [comment]
I'll take a look at this now.

**Comment by peterhil** [comment]
Thank you!

**Pull request merged**
